### ISSUE TITLE
Redesign the website

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider.github.io#175]
Now that GH pages moved to https, fonts are not loaded by our old theme.
I'm willing to redesign the whole site by using a modern, minimal and sleek theme (à la https://supercollider.github.io/sc3-plugins).. This would be my summer-holidays-present : ) 

-----

## 2021 update

I'm gonna propose a fresh new website, with a simple and modern design (mobile friendly).
Seeing that over the last 4 years there were no real consensus reached as to what content should or should not go I'm gonna propose something very minimal and if the community likes it someone can take over from there : )

-----

- [x] use modern `jekyll` folder structure
- [x] use mobile-first simple theme
- [x] remove cruft and keep concise minimal content
- [x] `.md` files over `.html` when possible
- [x] add a carousel/gallery with community projects
- [x] dedicated download page (we have too many possible downloads)
- [x] audio snippets for code examples

**Comment by snappizz** [comment]
hi @gusano, any new updates on the new update?

**Comment by gusano** [comment]
@snappizz got sucked in by the summer waves and I won't have time before first week of September but it's on my list

**Comment by snappizz** [comment]
cool, no pressure.

**Comment by snappizz** [comment]
@gusano i hate to be a pest, but if you have any work to show that would be great! if you don't plan to work on this, that's fine too, just let everyone know so someone else can step up.

**Comment by gusano** [comment]
@snappizz as soon as I'm back to civilization I'll work on it, should be in a week roughly.

**Comment by htor** [comment]
@gusano
let's discuss ideas for the new website. do you have any inspiring websites that may be a good starter for discussions? i'm thinking the supercollider website should be informative, easy to navigate and cleanly designed for the artist, programmer, technical person, musician, teacher and other types. but also playful/experimental.

maybe a short intro section (1. download, 2. install. 3. run code) would be nice to get new users onboard? also, given the experimental nature of sc, algorithmic composition and computer music it would be nice to have some content showing a snippet/performance/session (audio/video/image) or similar (look at the Videos section here https://www.haskell.org/) to demonstrate the capabilities of sc. the current website looks clean, but too clean. it's missing firstly some colourful content to make it shine, and it's missing an identity, in my opinion. i think the sc logos look good and clean, and we should consider them when designing something new.

<img width="140" alt="screen shot 2018-10-02 at 12 52 34" src="https://user-images.githubusercontent.com/1709263/46344622-0d6a1f80-c642-11e8-96c4-ad8c170da1d3.png"><img width="180" alt="screen shot 2018-10-02 at 11 22 19" src="https://user-images.githubusercontent.com/1709263/46344573-ea3f7000-c641-11e8-8324-f624f1352ee8.png"><img width="180" alt="screen shot 2018-10-02 at 11 22 19" src="https://user-images.githubusercontent.com/1709263/46344659-312d6580-c642-11e8-9f8c-73f669e92b08.png">

check out the old website too - it's rad: http://www.audiosynth.com/. disussion here https://scsynth.org/t/original-supercollider-website/311/6. on closer thought, maybe this discussion should be over at https://scsynth.org?

**Comment by gusano** [comment]
hiho @htor 
yeah the idea is to have a more modern design **wich works on mobile** (current design doesn't).
a couple of ideas:
- sleak minimal design (see http://supercollider.github.io/sc3-plugins/ or https://www.haskell.org/)
- basic fonts from google (current one looks ugly on linux)
- I like the videos idea
- done with modern jekyll so it's super easy to add content (already done but a cleanup might be a good idea, i.e. modern plugins for code highlight etc..)

I didn't plan it but I have few free time right now..
I'll post some design ideas here when I can

**Comment by geoffroymontel** [comment]
If you want, we can discuss what we want to show on the website on slack or on scsynth.org, and I can have a go at something and we iterate ?

**Comment by htor** [comment]
i started a thread here: https://scsynth.org/t/website-re-design/592. hope to get some good ideas flowing from people!
