### ISSUE TITLE
slack invite not working

### ISSUE THREAD

**Issue by styk-tv** [supercollider/supercollider.github.io#209]
On page:
https://supercollider.github.io/

<img width="559" alt="Screenshot 2019-12-25 at 11 34 06" src="https://user-images.githubusercontent.com/838921/71444607-83a4e700-270a-11ea-9c0e-9bb8366745b0.png">

pointing to: https://join.slack.com/t/scsynth/shared_invite/enQtMzk3OTY3MzE0MTAyLWY1ZGE1MTJjYmI5NTRkZjFmNjZmNmYxOWI0NDZkNjdkMzdkNjgxNTJhZGVlOTEwYjdjMDY5OWM0ZTA4NWFiOGY

takes the user to 

<img width="453" alt="Screenshot 2019-12-25 at 11 35 21" src="https://user-images.githubusercontent.com/838921/71444627-a800c380-270a-11ea-8156-a2e6803faee1.png">

Do we have an updated address?

**Comment by brianlheim** [comment]
yes, we recently updated the one in the main project readme and that one still works as far as i can tell: https://join.slack.com/t/scsynth/shared_invite/enQtMzk3OTY3MzE0MTAyLTFmMTliMmU0NjIwYzgyZGY1MjgxNGI2MGUxMTNlMWVhZWQzZjFmOTJhNzg2NDdmNzZmM2JiYTkyMjRiNDBiOTk

i'll update the one for the website presently
