### ISSUE TITLE
Slack / Scsynth?

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider.github.io#219]
sciss wrote on sc-dev:

> someone asked me how to see SC activity; since I'm no longer that
> involved, I thought I look it up on the page:
> 
> https://supercollider.github.io/
> 
> If you scroll down to Community, there is a link to 'Slack' but if you
> follow it, I get "This link is no longer active"
> 
> On the repo README.md, there is link to https://scsynth.org/
> 
> I think probably website should remove Slack link and add scsynth.org link.
>

**Comment by brianlheim** [comment]
was this a recent post? that link works, and there is a link to the Discourse form on the website too.

**Comment by telephon** [comment]
it was a month ago, I just noticed it for some reason and thought it was new. But if it is all there, fine!
