### ISSUE TITLE
Jekyll build broken locally

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider.github.io#248]
With a recent clone, building the site locally is broken:

```
ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>':
Document 'vendor/bundle/ruby/2.7.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb'
does not have a valid date in the YAML front matter.
```

- ArchLinux
- `ruby-2.7.3p183`

Re https://github.com/jekyll/jekyll/issues/5267

**Comment by dyfer** [comment]
I've tested this with ruby 3.0.0 on macOS and 1) I can't reproduce the original issue and 2) build from this PR still seems to build fine locally.

With 3.0.0 I had to however add `webrick` with `bundle add webrick`.

My knowledge of `jekyll` is very minimal. Do you think it's safe to pull this in? Also, possibly for another PR: should `webrick` be added to the Gemfile for compatibility with 3.0.0?
