### ISSUE TITLE
supercollider.github.io forensyc analysis results - hidden sections, how to access?

### ISSUE THREAD

**Issue by ahtoaXoov7D** [supercollider/supercollider.github.io#269]
<sub>i noticed throughout a forensic analysis, that just came up for the sake of learning some stuff related to websecurity, that the supercollider website, has some hidden sections, include, not only, but as well:</sub>

```
/news (Status: 200)]]
/images (Status: 301)
/index (Status: 200)
/links (Status: 200)
/downloads (Status: 200)
/projects (Status: 200)
/feed (Status: 200)
/releases (Status: 301)
/assets (Status: 301)
/book (Status: 301)
/courses (Status: 301)
/survey (Status: 301)
/development (Status: 301)
/uncategorized (Status: 301)
/examples (Status: 200)
/workshops (Status: 301)
/404 (Status: 200)
/symposium (Status: 301)
/2012 (Status: 301)
/meetups (Status: 301)
```

<sub>how can i access all those, and more important how can i copy the information which is there for my hard drive, and having it all neat and organized locally</sub>

**Comment by dyfer** [comment]
Hello, the source for the website is available in this repo. Any "hidden" sections are likely the result of some bundler/jekyll settings, i.e. nothing is explicitly hidden by the maintainers.
