### ISSUE TITLE
fix links on community page

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider.github.io#59]
In the preview they look fine:

https://github.com/supercollider/supercollider.github.io/blob/master/community/systems-interfacing-with-sc.md

but on the site it doesn't work:

http://supercollider.github.io/community/systems-interfacing-with-sc

the footnote style links do not work. They are messy to deal with anyway; all links should be inline.

**Comment by jamshark70** [comment]
Isn't the problem that the footnote links must all be at the bottom of the .md file, but some of them are in the middle?

Note that the links after "Editors" are perfectly OK. The broken ones are all toward the top, and the footnote defs are in the middle.
