### ISSUE TITLE
Improved projects page

### ISSUE THREAD

**Issue by madamdata** [supercollider/supercollider.github.io#63]
I think there should be a better-organized and more comprehensive page for projects done in SC. From my experience with other languages, one of the first questions I ask when coming to new software is "what can I do with this, and what have others done with it?". What the community is doing (and therefore what kind of projects they might be helpful with or have experience with) seems to me to be a crucial feature of any software project. A well-documented projects page can also serve as a repository of ideas and inspiration for future projects. I think these sentiments might be shared by a significant number of newcomers to SC. 

**Some features I think would be important:**
Embedded sound and video (youtube / soundcloud links)
a short blurb for each project summarizing what it is and how it uses SC
maybe categories for projects? Composition, sound installation, instrument, etc? 
snippets of code accessible straight from the browser, for projects where that makes sense

Examples of projects pages that I think do a good job(we don't necessarily have to copy these, but it's worth discussing whether we think they're good and how)

[https://cycling74.com/community/?q=project](https://cycling74.com/community/?q=project)
[https://processing.org/exhibition/](https://processing.org/exhibition/)

I particularly like the Processing projects page - it's concise, curated and has a lot of description up front. 

Let me know what you think!

**Comment by scztt** [comment]
I've been starting to do some ground-level research on setting this up. My intuition is a simple + nice looking wordpress page would provide more than enough to start hosting the kinds of content a SC exhibition page would initially need. Any comments on platform are welcome - WP seems to strike a good balance: it's open-source-oriented and highly modular, but also easy to set up and maintain, and doesn't require that contributors / stakeholders have any deep knowledge of web development stuff.

[sccode.org](http://sccode.org) handles code snippets very well already - a simple way to embed those in a page, plus an easy way for editors to create snippets for a post / article, would make the whole workflow really really slick.

I like the gallery format of the pages you mentioned - I also REALLY like Carl Testa's [SC Interviews blog](http://scinterviews.com/). In general, it would also be nice to have things that are a little more in-depth that the usual "gallery" overview as well - I like the idea of giving an SC user a spotlight to talk about how they made a particular synth sound good, how they made the parts of their system work together, how they solved a particular technical or artistic problem.

Finally - thinking of the recent discussions regarding diversity + inclusion in the SC community, I think this is a perfect chance to make sure there's a highly inclusive, global, heterogeneous group of people curating and represented in the content - something that reflects the *actual* scope of people using / uses of SC, and not just the narrow range that surface in the usual internet spaces. I'd like very much to help get this off the ground technically, but more than anything I'd like to hear some new voices in content of... whatever ends up being built.

**Comment by crucialfelix** [comment]
you can also embed gists into jekyll pages very easily and supercollider code now gets the correct syntax coloring.

you can create posts in a "projects" category and people should be able to just submit a PR with a new project page.  that's my only input. I'm sure you'll figure out the best way to do it.

**Comment by crucialfelix** [comment]
example medium post: https://medium.com/@crucialfelix/supercollider-js-0-9-5b534be26d74#.r5zijd40u

**Comment by bagong** [comment]
I would also love to see one of those mature content managements systems like Wordpress or Drupal as a base of the core SC site. It offers so much out of the box, could almost work like a FB group, and at the same time give a recognizable face to SC, plus offer the little special requirements. User management could be close to self-organizing, so no need for too much control from the center. The question for me would be how to avoid splitting the community even more and offer a significant value that makes people interested and wanting to care.

**Comment by crucialfelix** [comment]
I thought the point of the projects page was to get it on the main entrance for supercollider.github.io

Rebuilding the current site on wordpress is a whole separate (large) project.

**Comment by danstowell** [comment]
Everything comes back around again, given enough time. We used to be on Wordpress. Yes indeed it offered so much out of the box, it was also a pain to manage and started to fall apart. I would argue that the "static site generator" approach is best for long-term management of a low-resource open-source project.

Anyway I'd agree with Felix that a move to wordpress is a completely different idea from that of having a nice projects page. I'm no jekyll expert but maybe a nice way of doing it can be done with jekyll, and people can add projects as little pull-requests.

**Comment by bagong** [comment]
Well, both things need not exclude each other. Just depends on who is willing to do something, right. Using jekyll and pull requests means strong central control and techie only site. Frankly, I am not surprised that that is not - and has never been - a popular approach. Maybe the real question is whether the SC Github community wants to open itself actively to the other communities. I can see why some might prefer not to do so, it's a fair point that should be discussed openly.
As to the more ambitious alternative: a way to avoid further splitting up the community could be to use the site to work against it. For example the site could aggregate "news" from the various SC fora (sccode, FB, mailing lists, github tec...)

**Comment by scztt** [comment]
I don't think we should migrate anything from the current site - the github site works great for the kinds of content it current has. But it seems like Jekyll wouldn't be able to provide a nice looking multimedia gallery, text content, comments, device-independent, etc. setup that would be needed for an exhibition / projects site. We could probably get _close_ with jekyll, but it would require some very labor intensive site design and front-end work that would come for almost-free from something like WordPress, Tumblr, Squarespace, Medium (I mentioned WP because it seems like a better open source community presence than the others). Can someone find an example of a github-hosted jekyll site that's doing a nice exhibition/gallery-style presentation? Perhaps there's some untapped potential after all.

I don't see a reason, though, why we couldn't have a blog-appropriate CMS handle the blog/gallery page, and embed that on the github site? (For example: the [openFrameworks gallery page](http://openframeworks.cc/gallery/) is just tiled image links that point to creativeapplications articles)

**Comment by lijon** [comment]
Here's an example, made with Jekyll: http://processingjs.org/exhibition/
See their section about updating the exhibition in their README:
https://github.com/processing-js/processing-js.github.io/blob/master/README.md

As you see in
https://github.com/processing-js/processing-js.github.io/tree/master/exhibition
there's an index with some Liquid to generate the index page for it, then
each exhibition post is just a small html snippet. This snippet could be
written in markdown as well, I guess?

On Sun, Apr 17, 2016 at 11:27 PM, scztt <notifications@github.com> wrote:

> I don't think we should migrate anything from the current site - the
> github site works great for the kinds of content it current has. But it
> seems like Jekyll wouldn't be able to provide a nice looking multimedia
> gallery, text content, comments, device-independent, etc. setup that would
> be needed for an exhibition / projects site. We could probably get *close*
> with jekyll, but it would require some very labor intensive site design and
> front-end work that would come for almost-free from something like
> WordPress, Tumblr, Squarespace, Medium (I mentioned WP because it seems
> like a better open source community presence than the others). Can someone
> find an example of a github-hosted jekyll site that's doing a nice
> exhibition/gallery-style presentation? Perhaps there's some untapped
> potential after all.
>
> I don't see a reason, though, why we couldn't have a blog-appropriate CMS
> handle the blog/gallery page, and embed that on the github site? (For
> example: the openFrameworks gallery page
> <http://openframeworks.cc/gallery/> is just tiled image links that point
> to creativeapplications articles)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider.github.io/issues/63#issuecomment-211119493>
>



-- 
/Jonatan
http://kymatica.com

**Comment by crucialfelix** [comment]
That would work great: A projects website somewhere else where all the articles and content is listed and a simple index page of gallery on the github static site.

jekyll templates can contain anything; javascript could fetch a feed from another website and render a gallery.

or a simple folder like processing did it.

there are zillions of plugins for jekyll: http://www.jekyll-plugins.com/
slideshows, youtube, vimeo, thumbnailers, embed.ly (which will handle just about anything you want to embed), soundcloud

to write an article you just write markdown text and put your image, youtube, soundcloud, gist etc. in the body.  

but it is obvious from the lack of contribution to the current site that people find it foreign and unapproachable.

**Comment by telephon** [comment]
>but it is obvious from the lack of contribution to the current site that people find it foreign and unapproachable. 

Maybe in the past is has been more the pull-request-scheme of github that was foreign for those who had something to announce?

**Comment by miguel-negrao** [comment]
> but it is obvious from the lack of contribution to the current site that people find it foreign and unapproachable.
> 
> Maybe in the past is has been more the pull-request-scheme of github that was foreign for those who had something to announce?

In my case I tried to install the tools to build the pages locally once or twice and failed miserably (linux), gave up and went to do something else.

**Comment by bagong** [comment]
Hahaha. I actually managed to install the system on OSX (could preview the result). But I must still be missing something essential, as I edited literal html. I don't know until now where I would be supposed to enter MD ;)

**Comment by snappizz** [comment]
I'll work on this. What are some cool projects we could feature on the front page?

**Comment by telephon** [comment]
If we really want to take away some of the current coolness of understatement, it should at least be a wild mix of projects from all fields and all sizes.

**Comment by gusano** [comment]
The new design has this feature ;)
