### ISSUE TITLE
Raspberrypi instructions do not work

### ISSUE THREAD

**Issue by colinsullivan** [supercollider/supercollider.github.io#69]
http://supercollider.github.io/development/building-raspberrypi.html

Trying on a Raspberry PI 3 Model B.

Step 6.2:

>sclang #should start sc and compile the class library with only 3 harmless class overwrites warnings

	init_OSC
	empty
	compiling class library...
	initPassOne started
		NumPrimitives = 590
	initPassOne done
		compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
		pass 1 done
	ERROR: Class extension for nonexistent class 'Document'
	     In file:'/deprecated/3.7/deprecated-3.7.sc'
		numentries = 658972 / 6661008 = 0.099
		3672 method selectors, 1814 classes
		method table size 4425868 bytes, big table size 26644032
		Number of Symbols 8839
		Byte Code Size 251349
		compiled 219 files in 0.88 seconds

	Info: 3 methods are currently overwritten by extensions. To see which, execute:
	MethodOverride.printAll

	compile done
	Execution warning: Class 'NotificationCenter' not found
	ERROR: Message 'isMetaClass' not understood.
	RECEIVER:
	   nil
	ARGS:
	CALL STACK:
		DoesNotUnderstandError:reportError   0x13b5dd0
			arg this = <instance of DoesNotUnderstandError>
		Nil:handleError   0x13b5e30
			arg this = nil
			arg error = <instance of DoesNotUnderstandError>
		Thread:handleError   0x13b5e90
			arg this = <instance of Thread>
			arg error = <instance of DoesNotUnderstandError>
		Object:throw   0x13b60d0
			arg this = <instance of DoesNotUnderstandError>
		Object:doesNotUnderstand   0x13b63d0
			arg this = nil
			arg selector = 'isMetaClass'
			arg args = [*0]
		Meta_Class:initClassTree   0x13b64f0
			arg this = <instance of Meta_Class>
			arg aClass = nil
			var implementsInitClass = nil
		Meta_Server:initClass   0x13b2d90
			arg this = <instance of Meta_Server>
		Meta_Class:initClassTree   0x13b5ef0
			arg this = <instance of Meta_Class>
			arg aClass = <instance of Meta_Server>
			var implementsInitClass = nil
		Meta_Event:initClass   0x13b6370
			arg this = <instance of Meta_Event>
		Meta_Class:initClassTree   0x13b3170
			arg this = <instance of Meta_Class>
			arg aClass = <instance of Meta_Event>
			var implementsInitClass = nil
		Meta_EventTypesWithCleanup:initClass   0x13b4710
			arg this = <instance of Meta_EventTypesWithCleanup>
		Meta_Class:initClassTree   0x13b5f50
			arg this = <instance of Meta_Class>
			arg aClass = <instance of Meta_EventTypesWithCleanup>
			var implementsInitClass = nil
		ArrayedCollection:do   0x13b3230
			arg this = [*149]
			arg function = <instance of Function>
			var i = 27
		Meta_Class:initClassTree   0x13b2a30
			arg this = <instance of Meta_Class>
			arg aClass = <instance of Meta_Object>
			var implementsInitClass = nil
		Process:startup   0x13b20f0
			arg this = <instance of Main>
			var time = 0.899260664
		Main:startup   0x13b1310
			arg this = <instance of Main>
			var didWarnOverwrite = false
	^^ The preceding error dump is for ERROR: Message 'isMetaClass' not understood.
	RECEIVER: nil

	sc3> s.boot
	ERROR: Message 'boot' not understood.
	RECEIVER:
	   nil
	ARGS:
	CALL STACK:
		DoesNotUnderstandError:reportError   0x13b5230
			arg this = <instance of DoesNotUnderstandError>
		Nil:handleError   0x13b5290
			arg this = nil
			arg error = <instance of DoesNotUnderstandError>
		Thread:handleError   0x13b5350
			arg this = <instance of Thread>
			arg error = <instance of DoesNotUnderstandError>
		Object:throw   0x13b53b0
			arg this = <instance of DoesNotUnderstandError>
		Object:doesNotUnderstand   0x13b5530
			arg this = nil
			arg selector = 'boot'
			arg args = [*0]
		Interpreter:interpretPrintCmdLine   0x13b2df0
			arg this = <instance of Interpreter>
			var res = nil
			var func = <instance of Function>
			var code = "s.boot"
			var doc = nil
			var ideClass = nil
		Process:interpretPrintCmdLine   0x13b5770
			arg this = <instance of Main>
	^^ The preceding error dump is for ERROR: Message 'boot' not understood.
	RECEIVER: nil

	sc3>

Related: https://github.com/supercollider/supercollider/issues/1209

**Comment by redFrik** [comment]
worked for me just a few days ago.
are you sure you did all the steps in the right order?
specially export CC=/usr/bin/gcc-4.8 and export CXX=/usr/bin/g++-4.8.  iirc, the fix to #1209 is to compile with gcc 4.8.
_f

> 5 jun 2016 kl. 22:30 skrev Colin Sullivan <notifications@github.com>:
> 
> http://supercollider.github.io/development/building-raspberrypi.html
> 
> Trying on a Raspberry PI 3 Model B.
> 
> Step 6.2:
> 
> sclang #should start sc and compile the class library with only 3 harmless class overwrites warnings
> 
> init_OSC
> empty
> compiling class library...
> initPassOne started
>     NumPrimitives = 590
> initPassOne done
>     compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
>     pass 1 done
> ERROR: Class extension for nonexistent class 'Document'
>      In file:'/deprecated/3.7/deprecated-3.7.sc'
>     numentries = 658972 / 6661008 = 0.099
>     3672 method selectors, 1814 classes
>     method table size 4425868 bytes, big table size 26644032
>     Number of Symbols 8839
>     Byte Code Size 251349
>     compiled 219 files in 0.88 seconds
> 
> Info: 3 methods are currently overwritten by extensions. To see which, execute:
> MethodOverride.printAll
> 
> compile done
> Execution warning: Class 'NotificationCenter' not found
> ERROR: Message 'isMetaClass' not understood.
> RECEIVER:
>    nil
> ARGS:
> CALL STACK:
>     DoesNotUnderstandError:reportError   0x13b5dd0
>         arg this = <instance of DoesNotUnderstandError>
>     Nil:handleError   0x13b5e30
>         arg this = nil
>         arg error = <instance of DoesNotUnderstandError>
>     Thread:handleError   0x13b5e90
>         arg this = <instance of Thread>
>         arg error = <instance of DoesNotUnderstandError>
>     Object:throw   0x13b60d0
>         arg this = <instance of DoesNotUnderstandError>
>     Object:doesNotUnderstand   0x13b63d0
>         arg this = nil
>         arg selector = 'isMetaClass'
>         arg args = [*0]
>     Meta_Class:initClassTree   0x13b64f0
>         arg this = <instance of Meta_Class>
>         arg aClass = nil
>         var implementsInitClass = nil
>     Meta_Server:initClass   0x13b2d90
>         arg this = <instance of Meta_Server>
>     Meta_Class:initClassTree   0x13b5ef0
>         arg this = <instance of Meta_Class>
>         arg aClass = <instance of Meta_Server>
>         var implementsInitClass = nil
>     Meta_Event:initClass   0x13b6370
>         arg this = <instance of Meta_Event>
>     Meta_Class:initClassTree   0x13b3170
>         arg this = <instance of Meta_Class>
>         arg aClass = <instance of Meta_Event>
>         var implementsInitClass = nil
>     Meta_EventTypesWithCleanup:initClass   0x13b4710
>         arg this = <instance of Meta_EventTypesWithCleanup>
>     Meta_Class:initClassTree   0x13b5f50
>         arg this = <instance of Meta_Class>
>         arg aClass = <instance of Meta_EventTypesWithCleanup>
>         var implementsInitClass = nil
>     ArrayedCollection:do   0x13b3230
>         arg this = [*149]
>         arg function = <instance of Function>
>         var i = 27
>     Meta_Class:initClassTree   0x13b2a30
>         arg this = <instance of Meta_Class>
>         arg aClass = <instance of Meta_Object>
>         var implementsInitClass = nil
>     Process:startup   0x13b20f0
>         arg this = <instance of Main>
>         var time = 0.899260664
>     Main:startup   0x13b1310
>         arg this = <instance of Main>
>         var didWarnOverwrite = false
> ^^ The preceding error dump is for ERROR: Message 'isMetaClass' not understood.
> RECEIVER: nil
> 
> 
> sc3> s.boot
> ERROR: Message 'boot' not understood.
> RECEIVER:
>    nil
> ARGS:
> CALL STACK:
>     DoesNotUnderstandError:reportError   0x13b5230
>         arg this = <instance of DoesNotUnderstandError>
>     Nil:handleError   0x13b5290
>         arg this = nil
>         arg error = <instance of DoesNotUnderstandError>
>     Thread:handleError   0x13b5350
>         arg this = <instance of Thread>
>         arg error = <instance of DoesNotUnderstandError>
>     Object:throw   0x13b53b0
>         arg this = <instance of DoesNotUnderstandError>
>     Object:doesNotUnderstand   0x13b5530
>         arg this = nil
>         arg selector = 'boot'
>         arg args = [*0]
>     Interpreter:interpretPrintCmdLine   0x13b2df0
>         arg this = <instance of Interpreter>
>         var res = nil
>         var func = <instance of Function>
>         var code = "s.boot"
>         var doc = nil
>         var ideClass = nil
>     Process:interpretPrintCmdLine   0x13b5770
>         arg this = <instance of Main>
> ^^ The preceding error dump is for ERROR: Message 'boot' not understood.
> RECEIVER: nil
> 
> 
> sc3>
> 
> Related: supercollider/supercollider#1209
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


  #|
     fredrikolofsson.com     musicalfieldsforever.com
  |#

**Comment by colinsullivan** [comment]
Was on #Version-3.7.2, pulled from master and it worked.
