### ISSUE TITLE
Wiki migration is incomplete

### ISSUE THREAD

**Issue by nhthn** [supercollider/supercollider.github.io#86]
There's still some text and media on the wiki that hasn't been imported yet: http://supercollider.sourceforge.net/wiki/index.php/Special:AllPages

**Comment by crucialfelix** [comment]
I still think that most of the pages should be on github's easy normal wiki, not on the site.

ie. https://github.com/supercollider/supercollider/wiki

**Comment by snappizz** [comment]
https://github.com/supercollider/supercollider.github.io/projects/1

cc @brianlheim who offered to help with this

**Comment by brianlheim** [comment]
@snappizz - I just moved over one page from the wiki but now I'm confused. Should we put them here or on the main project wiki as @crucialfelix suggested? Personally, I would rather have them on the project wiki, for a few reasons:

- doesn't require extra work to preview
- the website wiki section probably needs to be redone anyway
- more wiki-type stuff has gone on the project wiki recently
- project wiki has access to github's supercollider syntax highlighting (github-pages STILL doesn't have it, i opened a PR at https://github.com/jneen/rouge a long time ago that's in limbo).

**Comment by crucialfelix** [comment]
I agree the github.io website shouldn't try to be the wiki. It's too slow and cumbersome and requires too many steps and learning for people to contribute. Even I would have to go figure out how to add or edit pages and I built the thing (years ago).

**Comment by brianlheim** [comment]
OK, I am going to move them to the wiki, will try to do at least one per day.

**Comment by crucialfelix** [comment]
You can do it all really fast.

clone https://github.com/supercollider/supercollider.wiki.git

You can work locally, en masse and add all pages in one fell swoop.

### get the source 

These are the options I thought of:

- Download all those old pages in original wiki syntax. I tried to get access years ago to the wiki source files but we never figured it out.   
  - There might be a pandoc converter for it.
- Scrape the web pages
  1. Do some find and replace to get rid of the headers / footers. 
  2. Use an html to markdown converter en masse.
  3. More find and replace
- Copy and paste off the screen

**Comment by madskjeldgaard** [comment]
hey guys. the coding guidelines link on the bottom of this page is dead, pointing to `code-style-cpp.html` which doesn't seem to exist on this repo. I'm wondering if it's a problem related to this wiki migration? 

https://supercollider.github.io/contributing/
